### ISSUE TITLE
unable to publish --tag=charts of 6.5 with laravel 7

### ISSUE THREAD

**Issue by asadullah097** [Chartisan/Charts#632]
Hello I am using laravel 7 and I installed consoletvs/charts the version of charts 6.5 is installed but when I publish  --tag=charts it gives me the error  "Unable to locate publishable resources."
php version is 7.2.5
![Capture](https://user-images.githubusercontent.com/38780235/97989224-0d7c1100-1e00-11eb-9be8-1cc0522f5a91.PNG)

**Comment by weeradach** [comment]
the same issue, Do you have solved this solution?

**Comment by asadullah097** [comment]
which other packages you have installed in your app? I solved another way I installed a new laravel setup and installed the charts there and then manually transferred the files.but waiting for the best solution the charts 5 was the best and easy the 6 and 7 are a complex little bit. try manually that helps you for now and also waiting for the better solution.
Thank you
